### ISSUE TITLE
High Priority - Update Help Center Content 

### ISSUE THREAD

**Issue by sarahlazarich** [bloom-housing/Bloom-Doorway#1]
Link: https://housingbayarea.mtc.ca.gov/help/questions
![image](https://github.com/bloom-housing/Bloom-Doorway/assets/118844176/54d75800-5458-4e11-b154-198a0211460c)

Update the content here to read: 

"Affordable housing is generally housing that is offered below market rate.  Ideally, your home is affordable when:

- Renters: You spend no more than 30% of your income on rent and utilities.
- Homeowners: You spend no more than 30% of your income on mortgage payments, taxes, insurance, utilities and other housing-related costs.

In the Bay Area, that percentage can be as high as 50% and still be considered affordable. If you open a listing on this portal, you can see a minimum income requirement. Property managers **try to** set these income requirements to ensure that you are not cost-burdened by the rent."

**Comment by iph-97** [comment]
Translations:

Spanish
La vivienda asequible es generalmente vivienda que se ofrece por debajo del precio del mercado. Idealmente, su casa es asequible cuando:
- Inquilinos: no gasta más del 30% de sus ingresos en alquiler y servicios públicos.
- Propietarios de vivienda: no gasta más del 30 % de sus ingresos en pagos de hipoteca, impuestos, seguros, servicios públicos y otros costos relacionados con la vivienda.
En el Área de la Bahía, ese porcentaje puede ser tan alto como el 50% y aun así considerarse asequible. Si abre una lista en este portal, puede ver un requisito de ingresos mínimos. Los administradores de propiedades intentan establecer estos requisitos de ingresos para asegurarse de que usted no tenga que pagar la carga del alquiler.

Traditional Chinese
經濟適用房通常是指低於市場價格的住房。理想情況下，您的房屋在以下情況下是負擔得起的：
- 租房者：您將不超過收入的 30% 用於租金和水電費。
- 房主：您將不超過收入的 30% 用於抵押貸款付款、稅收、保險、公用事業和其他與住房相關的費用。
在灣區，這一比例可能高達 50%，但仍然被認為是可以承受的。如果您在此門戶上打開列表，您可以看到最低收入要求。物業經理試圖設定這些收入要求，以確保您不會因租金而承受成本負擔。

Vietnamese
Nhà ở giá rẻ nói chung là nhà ở được chào bán dưới mức giá thị trường. Lý tưởng nhất là nhà của bạn có giá cả phải chăng khi:
- Người thuê nhà: Bạn chi không quá 30% thu nhập của mình cho tiền thuê nhà và các tiện ích.
- Chủ sở hữu nhà: Bạn chi không quá 30% thu nhập của mình cho các khoản thanh toán thế chấp, thuế, bảo hiểm, điện nước và các chi phí khác liên quan đến nhà ở.
Ở Vùng Vịnh, tỷ lệ đó có thể lên tới 50% và vẫn được coi là hợp túi tiền. Nếu bạn mở một danh sách trên cổng thông tin này, bạn có thể thấy yêu cầu về thu nhập tối thiểu. Các nhà quản lý tài sản cố gắng đặt ra các yêu cầu về thu nhập này để đảm bảo rằng bạn không phải chịu gánh nặng về chi phí thuê nhà.

Tagalog
Ang abot-kayang pabahay ay karaniwang pabahay na inaalok na mas mababa sa market rate. Sa isip, ang iyong bahay ay abot-kaya kapag:
- Mga Nangungupahan: Gumastos ka ng hindi hihigit sa 30% ng iyong kita sa upa at mga utility.
- Mga May-ari ng Bahay: Gumastos ka ng hindi hihigit sa 30% ng iyong kita sa mga pagbabayad ng mortgage, mga buwis, insurance, mga kagamitan at iba pang mga gastos na nauugnay sa pabahay.
Sa Bay Area, ang porsyentong iyon ay maaaring kasing taas ng 50% at maituturing pa rin na abot-kaya. Kung magbubukas ka ng isang listahan sa portal na ito, makikita mo ang isang minimum na kinakailangan sa kita. Sinusubukan ng mga tagapamahala ng ari-arian na itakda ang mga kinakailangan sa kita na ito upang matiyak na hindi ka mabigat sa gastos ng upa.

**Comment by emilyjablonski** [comment]
QA Notes: Ensure the new translations are visible ([env](https://dev.housingbayarea.mtc.ca.gov/))

**Comment by sarahlazarich** [comment]
this was released yest
