### ISSUE TITLE
Max monthly rent input missing validation

### ISSUE THREAD

**Issue by ColinBuyck** [bloom-housing/Bloom-Doorway#15]
On the listings filter home page, you can put letters and negative values into the max monthly rent input. This ticket is just to block those characters from being entered but the larger effort to better align the landing page form and listings page filter form with our use of react hook form is captured here #16 

QA Notes: https://dev.housingbayarea.mtc.ca.gov/
1) Try to enter negative values or letters unsuccessfully
2) Notice how the rent formats when clicking out of the field
3) Click view listings and observe that the results and filter reflect the previously entered field
4) Then go into the listings search modal and perform the same validation tests

Note: There's an edge case that if you type in a value like 1200.23 into the landing page, it will show results for 1200 and when opening the listings search modal it will only show 1200. The url search doesn't currently support decimals and it didn't seem worth the time to handle this case.

**Comment by sarahlazarich** [comment]
@ColinBuyck does this need reviews?  Or is it merged / ready for QA??

**Comment by ColinBuyck** [comment]
Ready for QA! Thanks for the reminder 🐛

**Comment by sarahlazarich** [comment]
lgtm
