### ISSUE TITLE
Checkbox text is misaligned

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/Bloom-Doorway#18]
![Screenshot 2023-08-02 at 11.42.49 AM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/675474e8-0279-4111-a462-4b3d33cee23a)

The labels next to the checkboxes should be centered.

**Comment by emilyjablonski** [comment]
QA Notes
[Env](https://dev.housingbayarea.mtc.ca.gov/)
The label text should now be centered with the check on the search box on the home page and the filter drawer on the listings page.

**Comment by sarahlazarich** [comment]
thank you!
