### ISSUE TITLE
Partners footer misaligned

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/Bloom-Doorway#19]
![Screenshot 2023-08-02 at 12.44.58 PM.png](https://images.zenhubusercontent.com/601c7ede5322cf8ac29d50c4/d6a1e5e2-b26f-4330-bd15-5141cf03eba8)

**Comment by emilyjablonski** [comment]
QA Notes
[Env](https://partners.dev.housingbayarea.mtc.ca.gov/sign-in)
Ensure that the partners portal footer matches [Bloom core dev](https://partners.bloom.exygy.dev/sign-in).

**Comment by sarahlazarich** [comment]
looks good!
