### ISSUE TITLE
Remove components if no changes

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/Bloom-Doorway#28]
There are a few components that exist in DUIC where there isn't actually any code difference between the UIC files and the DUIC files.

We can change all imports from the DUIC file to the UIC file for the following components that have no changes, and then remove the DUIC file.

* addTranslation
* AppearanceBorderType
* AppearanceStyleType
* ButtonGroupSpacing
* FieldSection
* formOptions
* Heading
* LinkButton
* PageHeader
* t

**Comment by KrissDrawing** [comment]
QA Notes: It's just code refactor, so [this page](https://dev.housingbayarea.mtc.ca.gov/) should work as before, there shouldn't be any visual changes caused by this PR.
