### ISSUE TITLE
Dropdown items overlap header

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/Bloom-Doorway#48]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEZGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07eb9c8c88bc138d7df3551342626ad65b241d96/Screenshot%202023-10-17%20at%2010.08.47%20AM.png)

This may be a UIC change, and should ensure it continues to work with the slightly different behavior in core.

**Comment by sarahlazarich** [comment]
fixed
