### ISSUE TITLE
Dwy: Listing Unable to Publish

### ISSUE THREAD

**Issue by iph-97** [bloom-housing/Bloom-Doorway#49]
Adega, a listing on Doorway, reported that when they tried to publish their listing, they got an error message. We were able to recreate the issue, and it seems that all of their required information is in order. This is a high priority issue. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2EvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--606a446c5382d2207fad04bd0814795b5c307b20/image.png)

**Comment by ludtkemorgan** [comment]
This has been resolved for this property by manually changing the status to active in the DB. A followup PR has been created to prevent this issue from happening again
