### ISSUE TITLE
Doorway site header on desktop w filipino overlaps content

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/Bloom-Doorway#50]
<img width="1103" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEhCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d094c1f6d258425e2d1591718a5db6beed2e5214/Screenshot%202024-03-07%20at%2011.04.50%E2%80%AFAM.png" alt="Screenshot 2024-03-07 at 11.04.50 AM.png" />

**Comment by emilyjablonski** [comment]
<img width="988" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBempDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9e9000827d3c9a72b522d9d342731e8310e36b0/Screenshot%202024-03-07%20at%2012.21.14%E2%80%AFPM.png" alt="Screenshot 2024-03-07 at 12.21.14 PM.png" />

**Comment by emilyjablonski** [comment]
![Screenshot 2024-03-07 at 12 21 14 PM](https://github.com/bloom-housing/Bloom-Doorway/assets/65367387/5c03bb42-a0a6-4da0-9fa9-3293bb6d721e)

**Comment by sarahlazarich** [comment]
seems fixed!
