### ISSUE TITLE
Request approval email

### ISSUE THREAD

**Issue by emilyjablonski** [bloom-housing/Bloom-Doorway#9]
When a partner requests approval, all super admins will get an email that mirrors the Figma linked below.

[Figma](https://www.figma.com/file/cNRVrLdz8cjXQdSr54BRao/Approval?type=design&node-id=1447-65839&mode=design&t=csbd63IejLlerYqa-0)

**Comment by emilyjablonski** [comment]
Pending visual designs for branded emails

**Comment by sarahlazarich** [comment]
closing, moved over
